### ISSUE TITLE
기술 조사

### ISSUE THREAD

**Issue by Highdown** [bbbjihan/SE_project2#10]
기술 작성

**Comment by Highdown** [comment]
stat 구조체를 st_mtime 을 활용하여 최근 수정 시간을 받아와 tm 구조체에 적용시켜 tm_mon과 tm_mday을 사용하여 월과 일을 비교할 수 있다.

**Comment by bbbjihan** [comment]
확인하였습니다. 감사합니다.

**Comment by TAEY00N** [comment]
확인했습니다.
