### ISSUE TITLE
기술 조사

### ISSUE THREAD

**Issue by TAEY00N** [bbbjihan/SE_project2#15]
sys/stat.h 헤더 파일에 정의되어 있는 stat 구조체의 멤버 변수 중 하나인 off_t st_size를 사용해 파일의 크기를 가져올 수 있습니다.
 두 파일의 크기를 비교하고 결과를 사용자에게 알려주기 위해 if-else 구문으로 경우의 수를 나누어 각기 다른 결과에 해당하는 문구를 출력합니다.

**Comment by bbbjihan** [comment]
확인했습니다👍👍

**Comment by Highdown** [comment]
확인했습니다.
