### ISSUE TITLE
코드 리뷰

### ISSUE THREAD

**Issue by TAEY00N** [bbbjihan/SE_project2#17]
파일의 크기가 2GB 이상인 경우 int 변수로는 충분히 표현이 되지 않을 수 있고, 크기는 음수로 표현되지 않아 형 변환이 필요하지 않다고 생각되어집니다. 다른 분들의 생각은 어떠신가요?

**Comment by bbbjihan** [comment]
``` c
#include <sys/stat.h>
struct stat{
  off_t st_size; // 파일 크기(바이트)
}
```
stat struct에서 st_size의 Dtype은 off_t입니다.
off_t는 파일 offset을 나타내기 위한 자료형으로 보이는데, type def된 long int형인 것으로 확인됩니다.
int 형변환을 포함하지 않아도 크게 문제되지 않을 것으로 보입니다.
https://learn.microsoft.com/ko-kr/cpp/c-runtime-library/standard-types?view=msvc-170

**Comment by Highdown** [comment]
확인했습니다.
