### ISSUE TITLE
기술 조사

### ISSUE THREAD

**Issue by bbbjihan** [bbbjihan/SE_project2#4]
함수 구현을 위한 기술 조사

**Comment by bbbjihan** [comment]
스켈레톤 코드에 명시된 tm struct인 time1과 time2에 대해 file1과 file2의 수정시각을 대입해주어야 하기 때문에 struct tm과 struct stat으로 파일 정보를 불러왔을 때 stat struct에서 수정 시각에 해당하는 멤버인 
```time_t st_mtime; /* time of last modification */```를 tm struct로 형변환해주는 함수를 찾아야 함.
localtime()함수를 활용하면 될 것으로 보여 localtime()함수에 대해 조사함
``` c
#include <time.h>
struct tm *localtime(const time_t *timeval);
```
https://www.ibm.com/docs/ko/i/7.3?topic=functions-localtime-convert-time

**Comment by Highdown** [comment]
확인했습니다

**Comment by TAEY00N** [comment]
확인했습니다.
